import { HiPhone, HiOutlineDotsHorizontal } from 'react-icons/hi'
import {
  MdDashboardCustomize,
  MdGroups,
  MdEmail,
  MdOutlineDashboardCustomize,
  MdOutlineColorLens,
  MdOutlineCategory,
  MdClose,
  MdOutlineDevicesOther,
} from 'react-icons/md'
// import { HiOutlineDotsHorizontal } from 'react-icons/hi';
import {
  IoBagCheck,
  IoHome,
  IoGiftSharp,
  IoReturnDownBackSharp,
  IoRadioButtonOn,
} from 'react-icons/io5'

import { HiMiniUserCircle, HiOutlineWrenchScrewdriver } from 'react-icons/hi2'
import { BsBoxSeam, BsStar, BsStarFill } from 'react-icons/bs'
import { AiOutlineEye, AiOutlineDownCircle } from 'react-icons/ai'
import { IoMdMenu, IoIosArrowForward } from 'react-icons/io'
import { FcGoogle } from 'react-icons/fc'
import {
  FaFacebook,
  FaShieldAlt,
  FaHeart,
  FaTruck,
  FaReply,
  FaTty,
  FaChevronDown,
  FaSortDown,
  FaCaretRight,
  FaRegEdit,
  FaUserEdit,
  FaSearch,
  FaUser,
  FaEye,
} from 'react-icons/fa'
import { ImBin } from 'react-icons/im'
import { RiLogoutCircleRLine, RiProductHuntLine } from 'react-icons/ri'
import { FaCartArrowDown } from 'react-icons/fa6'
import {
  TbCircleNumber1Filled,
  TbCircleNumber2Filled,
  TbCircleNumber3Filled,
  TbHexagonNumber1,
  TbHexagonNumber2,
  TbHexagonNumber3,
  TbHexagonNumber4,
  TbHexagonNumber5,
  TbHexagonNumber6,
  TbHexagonNumber7,
  TbHexagonNumber8,
  TbHexagonNumber9,
  TbCircleDashedNumber1,
  TbCircleDashedNumber2,
  TbCircleDashedNumber3,
  TbCircleDashedNumber4,
  TbCircleDashedNumber5,
  TbCircleDashedNumber6,
  TbCircleDashedNumber7,
  TbCircleDashedNumber8,
  TbCircleDashedNumber9,
} from 'react-icons/tb'
const icons = {
  HiPhone,
  MdEmail,
  IoBagCheck,
  HiMiniUserCircle,
  IoHome,
  BsBoxSeam,
  BsStar,
  BsStarFill,
  AiOutlineEye,
  IoMdMenu,
  FaHeart,
  IoIosArrowForward,
  FcGoogle,
  FaFacebook,
  FaShieldAlt,
  RiLogoutCircleRLine,
  FaTruck,
  IoGiftSharp,
  FaReply,
  FaTty,
  FaChevronDown,
  HiOutlineDotsHorizontal,
  MdDashboardCustomize,
  MdGroups,
  RiProductHuntLine,
  FaCartArrowDown,
  AiOutlineDownCircle,
  FaSortDown,
  FaCaretRight,
  ImBin,
  FaRegEdit,
  MdOutlineDashboardCustomize,
  MdOutlineColorLens,
  MdOutlineCategory,
  MdOutlineDevicesOther,
  IoReturnDownBackSharp,
  MdClose,
  FaUserEdit,
  FaUser,
  FaEye,
  FaSearch,
  HiOutlineWrenchScrewdriver,
  TbCircleNumber1Filled,
  TbCircleNumber2Filled,
  TbCircleNumber3Filled,
  TbHexagonNumber1,
  TbHexagonNumber2,
  TbHexagonNumber3,
  TbHexagonNumber4,
  TbHexagonNumber5,
  TbHexagonNumber6,
  TbHexagonNumber7,
  TbHexagonNumber8,
  TbHexagonNumber9,
  TbCircleDashedNumber1,
  TbCircleDashedNumber2,
  TbCircleDashedNumber3,
  TbCircleDashedNumber4,
  TbCircleDashedNumber5,
  TbCircleDashedNumber6,
  TbCircleDashedNumber7,
  TbCircleDashedNumber8,
  TbCircleDashedNumber9,
  IoRadioButtonOn,
}

export default icons
